# This is a basic workflow to help you get started with Actions

name: 'Self hosted runner demo'

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello-self-hosted-runner:
    # The type of runner that the job will run on
    name: self hosted run.
    runs-on: [self-hosted, Windows, x64, gpu, production]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: run-me-inside-self-hosted-runner
        run: echo "Howdy I kknow I'm running in side the self hosted runner."
          
      - name: sleep for 100 seconds 
        run: sleep 100 
